apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: webshop-frontend
build:
  artifacts:
    - image: pcpartsshop/frontend
      sync:
        infer:
          - '**/*.js'
          - '**/*.css'
          - '**/*.jsx'
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/*
