apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          # Docker Image
          image: sa/react-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            #the port on which the app can be reached out inside the container
            - containerPort: 3000
