apiVersion: v1
kind: Service
metadata:
  #the Serivce Name- it should match with the lable name of the deployment 
  name: frontend
spec:
  #type of the service
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005
  type: NodePort
